# Exploring our original news datasets and filtering them to only what we need

In [20]:
import pandas as pd
import warnings

warnings.filterwarnings(
    "ignore", category=FutureWarning, message=".*un-recognized timezone.*"
)

In [21]:
df_cnbc = pd.read_csv("../../data/news/original/cnbc_headlines.csv")
df_guardian = pd.read_csv("../../data/news/original/guardian_headlines.csv")
df_reuters = pd.read_csv("../../data/news/original/reuters_headlines.csv")

### I'll start with just the CNBC data and then do the other two at the end once I know what to do

In [22]:
df_cnbc.head()

,Headlines,Time,Description
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying..."
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
2,NaN,NaN,NaN
3,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co..."
4,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be..."

It looks like we have some null rows, lets drop those

In [23]:
df_cnbc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3080 entries, 0 to 3079
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Headlines    2800 non-null   object
 1   Time         2800 non-null   object
 2   Description  2800 non-null   object
dtypes: object(3)
memory usage: 72.3+ KB

In [24]:
df_cnbc.dropna(inplace=True)
df_cnbc.reset_index(drop=True, inplace=True)

In [25]:
df_cnbc.head()

,Headlines,Time,Description
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying..."
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin..."
2,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co..."
3,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be..."
4,Wall Street delivered the 'kind of pullback I'...,"7:36 PM ET Thu, 16 July 2020","""Look for the stocks of high-quality companies..."

In [26]:
df_cnbc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2800 entries, 0 to 2799
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Headlines    2800 non-null   object
 1   Time         2800 non-null   object
 2   Description  2800 non-null   object
dtypes: object(3)
memory usage: 65.8+ KB

Around 280 rows had empty entries for some reason, hopefully after adding the data from other news sources we will still have enough headlines to work with. We still have 2800.

Let's also check the range of our data as we need to know this for later when we start matching news to stock prices.

In [27]:
df_cnbc['date'] = pd.to_datetime(df_cnbc['Time'], format='mixed')
min_date_cnbc = df_cnbc['date'].min()
max_date_cnbc = df_cnbc['date'].max()
print(min_date_cnbc)
print(max_date_cnbc)

2017-12-22 18:52:00
2020-07-17 19:51:00

To make things easier I'll combine the headline and description into a single summary field.

In [28]:
df_cnbc["summary"] = (
    df_cnbc["Headlines"].fillna("").astype(str).str.strip()
    + " "
    + df_cnbc["Description"].fillna("").astype(str).str.strip()
).str.strip()

df_cnbc.head()

,Headlines,Time,Description,date,summary
0,Jim Cramer: A better way to invest in the Covi...,"7:51 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer recommended buying...",2020-07-17 19:51:00,Jim Cramer: A better way to invest in the Covi...
1,Cramer's lightning round: I would own Teradyne,"7:33 PM ET Fri, 17 July 2020","""Mad Money"" host Jim Cramer rings the lightnin...",2020-07-17 19:33:00,Cramer's lightning round: I would own Teradyne...
2,"Cramer's week ahead: Big week for earnings, ev...","7:25 PM ET Fri, 17 July 2020","""We'll pay more for the earnings of the non-Co...",2020-07-17 19:25:00,"Cramer's week ahead: Big week for earnings, ev..."
3,IQ Capital CEO Keith Bliss says tech and healt...,"4:24 PM ET Fri, 17 July 2020","Keith Bliss, IQ Capital CEO, joins ""Closing Be...",2020-07-17 16:24:00,IQ Capital CEO Keith Bliss says tech and healt...
4,Wall Street delivered the 'kind of pullback I'...,"7:36 PM ET Thu, 16 July 2020","""Look for the stocks of high-quality companies...",2020-07-16 19:36:00,Wall Street delivered the 'kind of pullback I'...

I'll save the cleaned data to a new CSV file for later use when we make our models. Before I save I'll also specify which source it came from in case we want to know that later and maybe compare how accurate different sources are?

In [29]:
df_cnbc["source"] = "cnbc"

In [ ]:
df_cnbc[["date", "summary", "source"]].to_csv("../../data/news/filtered/cnbc_filtered.csv", index=False)

OSError: Cannot save file into a non-existent directory: 'data\news\filtered'

We will fully clean the data in a separate notebook later, for now we just want to get rid of any obviously unusable data.

I'll do the same for the other two datasets now.

## Reuters data filtering

In [ ]:
df_reuters.head()

,Headlines,Time,Description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...
3,Twitter says attackers downloaded data from up...,Jul 18 2020,Twitter Inc said on Saturday that hackers were...
4,U.S. Republicans seek liability protections as...,Jul 17 2020,A battle in the U.S. Congress over a new coron...

In [ ]:
df_reuters.dropna(inplace=True)
df_reuters.reset_index(drop=True, inplace=True)

df_reuters["date"] = pd.to_datetime(df_reuters["Time"], format="mixed")
min_date_reuters = df_reuters["date"].min()
max_date_reuters = df_reuters["date"].max()

df_reuters["summary"] = (
    df_reuters["Headlines"].fillna("").astype(str).str.strip()
    + " "
    + df_reuters["Description"].fillna("").astype(str).str.strip()
).str.strip()

df_reuters["source"] = "reuters"

df_reuters[["date", "summary", "source"]].to_csv(
    "../../data/news/filtered/reuters_filtered.csv", index=False
)

Worth noting that Reuters data only has the day and not the time, so we may need to account for that later when matching to stock prices.

## Guardian data filtering

In [ ]:
df_guardian.head()

        Time                                          Headlines
0  18-Jul-20   Johnson is asking Santa for a Christmas recovery
1  18-Jul-20  ‘I now fear the worst’: four grim tales of wor...
2  18-Jul-20  Five key areas Sunak must tackle to serve up e...
3  18-Jul-20  Covid-19 leaves firms ‘fatally ill-prepared’ f...
4  18-Jul-20  The Week in Patriarchy  \r\n\r\n\r\n  Bacardi'...

Already only has one column for the article text so we don't need to combine anything here.

In [ ]:
df_guardian.dropna(inplace=True)
df_guardian.reset_index(drop=True, inplace=True)

df_guardian["date"] = pd.to_datetime(df_guardian["Time"], format="mixed", errors="coerce")
df_guardian.dropna(inplace=True) # remove rows where date conversion failed
df_guardian.reset_index(drop=True, inplace=True)

min_date_guardian = df_guardian["date"].min()
max_date_guardian = df_guardian["date"].max()

df_guardian["summary"] = (
    df_guardian["Headlines"].fillna("").astype(str).str.strip()
).str.strip()

df_guardian["source"] = "guardian"

df_guardian[["date", "summary", "source"]].to_csv(
    "../../data/news/filtered/guardian_filtered.csv", index=False
)

### Now that we have separate CSV files, lets see what ranges each used

In [ ]:
print("CNBC date range:", min_date_cnbc, "to", max_date_cnbc)
print("Reuters date range:", min_date_reuters, "to", max_date_reuters)
print("Guardian date range:", min_date_guardian, "to", max_date_guardian)

CNBC date range: 2017-12-22 18:52:00 to 2020-07-17 19:51:00
Reuters date range: 2018-03-20 00:00:00 to 2020-07-18 00:00:00
Guardian date range: 2017-12-17 00:00:00 to 2020-07-18 00:00:00

It looks like if we combine them into one dataset, we will have data from 2017-12-17 to 2020-07-18, although the first three months won't have data from all three sources. That won't be an issue unless we compare sources, but that isn't the plan right now so let's just combine it all.

In [ ]:
df_cnbc_filtered = pd.read_csv(
    "../../data/news/filtered/cnbc_filtered.csv", parse_dates=["date"]
)
df_guardian_filtered = pd.read_csv(
    "../../data/news/filtered/guardian_filtered.csv", parse_dates=["date"]
)
df_reuters_filtered = pd.read_csv(
    "../../data/news/filtered/reuters_filtered.csv", parse_dates=["date"]
)

df_all = pd.concat(
    [df_cnbc_filtered, df_guardian_filtered, df_reuters_filtered], ignore_index=True
)
df_all.to_csv("../../data/news/filtered/all_filtered.csv", index=False)

df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53330 entries, 0 to 53329
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     53330 non-null  datetime64[ns]
 1   summary  53330 non-null  object
 2   source   53330 non-null  object
dtypes: datetime64[ns](1), object(2)
memory usage: 1.2+ MB

53k rows should be plenty for our purposes? Hopefully.

I forgot what the data looked like, putting this here for reference

In [ ]:
df_all.head()

,date,summary,source
0,2020-07-17 19:51:00,Jim Cramer: A better way to invest in the Covi...,cnbc
1,2020-07-17 19:33:00,Cramer's lightning round: I would own Teradyne...,cnbc
2,2020-07-17 19:25:00,"Cramer's week ahead: Big week for earnings, ev...",cnbc
3,2020-07-17 16:24:00,IQ Capital CEO Keith Bliss says tech and healt...,cnbc
4,2020-07-16 19:36:00,Wall Street delivered the 'kind of pullback I'...,cnbc

NOTE FOR LATER!!! 

the stock market closes at 6pm so we should